mode=association
input_file=./april25/input_association.txt
start_ind=0
end_ind=-1
output_file=./august25/output_association.txt
plot=false
write_chains=false
write_log=false
print_summary=false
nPoints=1
c1=3.205
c2=3.545
c3=4.512
c4=4.138
