mode=association
input_file=./april25/input_association.txt
start_ind=0
end_ind=-1
output_file=./april25/output_association_correlations.txt
plot=false
write_chains=false
write_log=false
print_summary=false
nPoints=1
c1=2.79
c2=3.16
c3=4.08
c4=3.83
