mode=association
input_file=./data/golden_input.txt
start_ind=0
end_ind=10
output_file=./data/golden_out.txt
plot=false
write_chains=false
write_log=false
print_summary=false
c1=3.205
c2=3.545
c3=4.512
c4=4.138
